# Generated by Django 2.1.7 on 2019-03-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desciption', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('posterURL', models.URLField()),
                ('releaseDate', models.DateField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
