# Generated by Django 2.1.7 on 2019-03-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyMovie', '0003_auto_20190330_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theatre',
            options={'verbose_name': 'Theatre', 'verbose_name_plural': 'Theatres'},
        ),
        migrations.AlterField(
            model_name='showtime',
            name='time',
            field=models.CharField(max_length=10, verbose_name='Time'),
        ),
    ]
