# Generated by Django 2.1.7 on 2019-03-30 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookMyMovie', '0004_auto_20190331_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(max_length=100, verbose_name='Seats')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='Booking timestamp')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyMovie.Movie', verbose_name='Movie')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyMovie.ShowTime', verbose_name='Show')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyMovie.Theatre', verbose_name='Theatre')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
