# Generated by Django 2.1.7 on 2019-04-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyMovie', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbID',
            field=models.CharField(default=1, max_length=50, verbose_name='IMDB_ID'),
            preserve_default=False,
        ),
    ]
