# Generated by Django 2.1.7 on 2019-04-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyMovie', '0006_movie_imdbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='desciption',
            new_name='description',
        ),
    ]
