# Generated by Django 2.1.7 on 2019-04-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyMovie', '0007_auto_20190406_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ShowDay',
                'verbose_name_plural': 'ShowDays',
            },
        ),
        migrations.AlterField(
            model_name='showtime',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyMovie.ShowDay', verbose_name=''),
        ),
    ]
