# Generated by Django 2.1.7 on 2019-04-14 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookMyMovie', '0008_auto_20190407_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='TheatreID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BookMyMovie.Theatre', verbose_name='Theatre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showtime',
            name='movieID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='BookMyMovie.Movie', verbose_name='movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showtime',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMyMovie.ShowDay', verbose_name='ShowDay'),
        ),
    ]
